[project]
authors = ["Erik van Onselen <erik.vanonselen@deltares.nl>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "sst-examples"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
jupyter = "*"
ipykernel = "*"
pip = "*"
scikit-learn = "*"
numpy = "*"
pandas = "*"
xgboost = "*"
seaborn = "*"
shap = "*"

[pypi-dependencies]
geost = ">=0.2.4, <0.3"
